version: '3.1'

services:

  proxy:
    build: ./reverse-proxy
    image: yuttasakcom/rexpress-proxy:1.13.7-alpine
    container_name: proxy
    networks:
      - proxy
    ports:
      - "80:80"
    restart: always

  rexpress:
    build: .
    image: yuttasakcom/rexpress-node:9.3.0-alpine
    container_name: rexpress
    volumes:
      - .:/opt/app
    environment:
      - PORT=80
      - NODE_ENV=production
    networks:
      - proxy
    restart: always

networks:
  proxy:
    driver: bridge