version: '3.1'

services:

  proxy:
    build: ./reverse-proxy
    container_name: proxy
    networks:
      - proxy
    ports:
      - "80:80"
    restart: always

  rexpress:
    build: .
    container_name: rexpress
    volumes:
      - .:/opt/app
      - notused:/opt/app/build
      - notused:/opt/app/public
    environment:
      - PORT=80
      - NODE_ENV=production
    networks:
      - proxy
    restart: always

volumes:
  notused:

networks:
  proxy:
    driver: bridge